### ISSUE TITLE
GUIs for Loot Fabricator and Simulation Chamber may display current FE stored from uninitialized memory

### ISSUE THREAD

**Issue by James103** [Shadows-of-Fire/Hostile-Neural-Networks#14]
Hostile Neural Networks 3.1.1
Minecraft 1.18.2
Forge 40.1.19

When a Loot Fabricator or Simulation Chamber's UI is opened, the first energy value displayed (the number X in "X/Y FE" that's shown when hovering over the energy bar) may come from uninitialized memory and is only updated next time the energy stored in the block updates.

For example, a fully-charged Simulation Chamber or one that's not gaining or losing power may appear to have a very high or very low (including negative) amount of FE stored within according to the GUI, but next time the energy stored updates, the actual value is sent to the client, overwriting the garbage data.

![image](https://user-images.githubusercontent.com/37945304/168456313-f6c96590-ded7-431b-adda-f7d4025002c1.png)

**Comment by Shadows-of-Fire** [comment]
This *should* be fixed in Placebo 6.4.2.  Technically that's not uninitialized memory but rather a copy of the lower 16 bits of the number being copied into the upper 16 bits.
