### ISSUE TITLE
HostileNetworks.VERSION in code is incorrect

### ISSUE THREAD

**Issue by James103** [Shadows-of-Fire/Hostile-Neural-Networks#15]
The version indicated in HostileNetworks.VERSION for Hostile Neutral Networks is outdated. It says "3.0.5" when it should say "3.1.1" (next: "3.1.2").
https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/blob/9c8787f8f3933a35b409d333f269ad39511c7183/src/main/java/shadows/hostilenetworks/HostileNetworks.java#L47

This is exposed to the user's GUI via the following:
https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/blob/9c8787f8f3933a35b409d333f269ad39511c7183/src/main/java/shadows/hostilenetworks/gui/SimChamberScreen.java#L176

**Comment by Shadows-of-Fire** [comment]
Yeah I forget to change this regularly... I need to change it to be replaced on build.  It's just a cosmetic thing
