### ISSUE TITLE
Allow one data model to represent multiple related/duplicate entity types

### ISSUE THREAD

**Issue by James103** [Shadows-of-Fire/Hostile-Neural-Networks#16]
Currently, each data model can only represent one entity.
This is problematic as some mod packs (including one with both this mod and Tinkers' Construct) may have two or more entities that look similar, behave similar, and have similar drops to each other, or that are exactly the same except their type IDs are different.

For example, Tinkers' Construct allows slimes to spawn on special islands, but those slimes have the ID `tconstruct:earth_slime` for the green slimes that are similar in looks, drops, and behavior to the vanilla `minecraft:slime`.

To rectify this and allow unification, I propose allowing each entity model to map to a tag (group) of entities.

Example usage in datapack:
`data/hostilenetworks/data_models/slime.json`
```json
{
	"type": "minecraft:slime",
	"tag": "#hostilenetworks:slimes",
	"name": "entity.minecraft.slime",
	...
}
```
`data/hostilenetworks/tags/entity_types/slimes.json`
```json
{
	"replace": false,
	"values": {
		"minecraft:slime",
		{"id": "tconstruct:earth_slime", "required": "false"}
	}
}
```

**Comment by Shadows-of-Fire** [comment]
A main problem with this is how do you convey that information to the user - how can they discern that an earth slime falls under the category of slime?

**Comment by James103** [comment]
There could be info in the lore of the item that says something along the lines of:
```
Tier: Faulty
Data Collected: 0/6
Data Per Kill: 1
Simulation Cost: 160 FE/t
Species:
- Slime
- Slime
```
where the last three lines are newly added information.
(The earth slime from Tinkers' Construct is actually called "Slime", but they're still a different ID compared to vanilla slimes)


The entity type rendered in the model could cycle through the represented species at a frequency of one hertz. For slimes, that would just be a color change once per second, but if all three main types of Overworld zombies (regular, husk, and drowned) are represented in one model, then the item would render a zombie for a second, then the next second it would render a husk, followed by a drowned before cycling back to zombie.


The lore for a custom model that represents the three main zombies could be:
```
Tier: Faulty
Data Collected: 0/18
Data Per Kill: 1
Simulation Cost: 240 FE/t
Species:
- Zombie
- Husk
- Drowned
```

**Comment by Shadows-of-Fire** [comment]
Subtypes have now been implemented through the json key `subtypes`, ex:
```json
"subtypes": [
	"minecraft:stray"
]
```

Variants will now rotate in the Deep Learner screen.

https://user-images.githubusercontent.com/3682588/179343720-2bef2f57-20c2-468d-8773-046354b906e2.mp4

They will also be shown on data model tooltips:
![](https://i.imgur.com/cqqrWMP.png)

**Comment by Shadows-of-Fire** [comment]
Another important thing to note is that subtypes are optional - you can add subtypes that may not necessarily be loaded into the game.
This allows the TiC earth slime to be added to the default subtypes of the slime model.
