### ISSUE TITLE
Data model not progressing.

### ISSUE THREAD

**Issue by slimeyena** [Shadows-of-Fire/Hostile-Neural-Networks#18]
Hiya, for example I am holding the skeleton data model, when I kill skeletons with it in my inventory or in the offhand it doesn't progress at all. I heard that you have to get the last hit with the data model and I tried that but nothing seems to work.

Are there any known incompatibilities? Everything in question appears to be vanilla from JEI. Have tried with skeletons from a skeleton spawner in survival and creative.

Any help is massively appreciated as I'm looking to throw this in a modpack as a part of progression.

**Comment by Shadows-of-Fire** [comment]
The data model has to be inside a deep learner to gain progress from kills.  That deep learner has to be inside your inventory, and the deep learner hud only shows if the DL is in your hand.
