### ISSUE TITLE
Shift Clicking into anything in Neural Nets causes crash

### ISSUE THREAD

**Issue by TheDyreBanana** [Shadows-of-Fire/Hostile-Neural-Networks#2]
Versions 3.0.2 Minecraft 1.18.1 forge

**Comment by Shadows-of-Fire** [comment]
So this one I've tested and it doesn't crash in dev, so, crash report is required here

**Comment by TheDyreBanana** [comment]
https://pastebin.com/3uTMhAXn

**Comment by Shadows-of-Fire** [comment]
Fixed in Placebo 6.0.2
