### ISSUE TITLE
Allow custom data models to produce nothing for its base_drop

### ISSUE THREAD

**Issue by iconmaster5326** [Shadows-of-Fire/Hostile-Neural-Networks#23]
Currently, omitting `base_drop` from a custom data model is an error. I have a modded mob that doesn't come from anywhere in particular, and I would like to have the base output of the operation be nothing at all. Currently, this use case doesn't seem supported!

**Comment by Shadows-of-Fire** [comment]
DML originally designed it such that new models added a new generic item, and it can be anything, it doesnt have to be a generic prediction item.

I may be able to support an empty base drop but it would make simulating a low tier model just awful.

**Comment by iconmaster5326** [comment]
The drop you get from the specific prediction I have in mind is very, very good, so this (plus a very high energy cost) is helping to balance things out. Currently, I'm making it produce a useless item for the `base_drop`, but I thought I'd throw a suggestion in for my use case.
