### ISSUE TITLE
Data Model not processing on Multipayer Server

### ISSUE THREAD

**Issue by TrickShotMLG02** [Shadows-of-Fire/Hostile-Neural-Networks#25]
I created a multiplayer server some time ago running the atm6 modpack. Now we reached the point where we were able to make use of the hostile neural network mod.

My friend knows this mod pretty well and showed me how everything works. The only problem is, that the data models are not processing on the server. When i test the same thing in Singleplayer, everything works fine.

Anybody got an idea how to fix that?

**Comment by Shadows-of-Fire** [comment]
What do you mean by "not processing"?

**Comment by TrickShotMLG02** [comment]
it always shows 0/6 kills

**Comment by Shadows-of-Fire** [comment]
So "not progressing" then.  Is the model in a deep learner?

**Comment by TrickShotMLG02** [comment]
yes

**Comment by TrickShotMLG02** [comment]
![2022-12-26_16 27 30](https://user-images.githubusercontent.com/43967908/209563620-39a503c2-80d1-4bdd-9436-fe8b59e97cfc.png)
![2022-12-26_16 27 36](https://user-images.githubusercontent.com/43967908/209563628-4a1ab2ac-3160-4f2b-908e-46a17af74e45.png)

**Comment by TrickShotMLG02** [comment]
Do you have an idea how to fix that?

**Comment by Shadows-of-Fire** [comment]
No, I've never had reported or seen an issue encountered with the deep learner specifically on servers.

Given that you're in atm6, there won't be any new releases for mc 1.16, so you'll want to ask around the modpack to see if they know what's happening.
