### ISSUE TITLE
Cannot use Data Models in custom recipes

### ISSUE THREAD

**Issue by aaronhowser1** [Shadows-of-Fire/Hostile-Neural-Networks#28]
I'm trying to make a custom recipe with KubeJS, and I want to use a Self Aware Enderman Model in it.

![image](https://user-images.githubusercontent.com/15698722/220503320-912bebe9-f168-451a-833b-5d47faabb891.png)

KubeJS:
```js
recipe.shaped('enderstorage:ender_chest',[
		' H ',
		' P ',
		' C '
	],{
		P: 'enderstorage:ender_pouch',
		C: 'minecraft:ender_chest',
		H: Item.of('hostilenetworks:data_model', '{data_model:{data:1271,id:"hostilenetworks:enderman"}}')
	})
```

As far as I can see, the data model doesn't include any special nbt that would be breaking this. My first assumption was that each model's nbt was actually just a pointer to the actual information, but no it's just right there. Any idea why this wouldn't be working?

**Comment by Shadows-of-Fire** [comment]
If the nbt matches exactly the nbt you would see on the real item, it should be working as expected, which leads me to think there may be some sort of mismatch between the "real" item and the "ingredient" item.

Did you write the nbt manually or did you get it from the kjs hand command (or whatever copies your held item into kjs form)?

**Comment by aaronhowser1** [comment]
I did `/kjs_hand`

**Comment by Shadows-of-Fire** [comment]
Well that's even more bizzare then.  Can you use a mod which dumps nbt to tooltip to verify that the item shown in jei has the right nbt?

Also, check if the recipe works as intended.  It might be a jei issue we're seeing

**Comment by aaronhowser1** [comment]
I did use `/ftblibrary nbtedit item` to set the NBT, by manually pushing `data` up until it says Self Aware (specifically, going up until I was 1 below Self Aware and then killing another one)

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/220507953-c5c28cf0-b58e-4135-bd7d-83f99beef983.png)
`{Count:1b,id:"hostilenetworks:data_model",tag:{data_model:{data:1271,id:"hostilenetworks:enderman"}}}`

![image](https://user-images.githubusercontent.com/15698722/220507998-532c65f6-a826-4b08-a702-a20a3f7872ba.png)

Using https://www.curseforge.com/minecraft/mc-mods/item-nbt-viewer: 
![image](https://user-images.githubusercontent.com/15698722/220509135-349ad195-4e86-4f32-9996-8a4cb8734895.png)

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/220509226-cc6b86c2-b84f-4f79-9914-7dd1d6538671.png)
![image](https://user-images.githubusercontent.com/15698722/220509239-eb4796e4-2258-49f3-afa9-f745ac104101.png)
huh.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/220511107-53fee609-db01-4272-8174-a682e1575107.png)
actually this might just be a problem with KubeJS, I'm going to try with a random other NBT-item from another mod to see.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/220511335-0cbc3408-c3ff-4b59-9dfa-3e9612357ad7.png)
Yep, this tank should have stuff in it. Sorry for the confusion, I'll report to KubeJS!
