### ISSUE TITLE
Self-aware Tier Models are bugged.

### ISSUE THREAD

**Issue by Rainmaykr** [Shadows-of-Fire/Hostile-Neural-Networks#3]
![blaze_model](https://user-images.githubusercontent.com/96355372/146655374-6d424bfe-566f-4bab-b481-38edc2cf4a8e.png)

Self-aware tier models are not operating at 99.5% success rate and appear to be bugged.

HostileNeuralNetworks-1.16.5-1.0.2

**Comment by Shadows-of-Fire** [comment]
Yeah this was recently fixed on 1.18, it just needs to be backported

**Comment by Shadows-of-Fire** [comment]
fixed in 1.0.3
