### ISSUE TITLE
Deep Learner vanishes from my inventory and bugged UI

### ISSUE THREAD

**Issue by mmouradev** [Shadows-of-Fire/Hostile-Neural-Networks#30]
Context: I'm playing on ATM8, and I died with deep learner in offhand when I grabbed my grave the deep learner did not appear on my inventory but the UI was still bugged.
I built another deep learner but when I take it out of hand the UI is still buggy.

![Minecraft_ 1 19 2 - Multiplayer (3rd-party Server) 08_03_2023 09_52_30](https://user-images.githubusercontent.com/20447581/223718272-4c171700-e58d-4a91-bc2d-0ba39239cbc6.png)
![Minecraft_ 1 19 2 - Multiplayer (3rd-party Server) 08_03_2023 09_52_43](https://user-images.githubusercontent.com/20447581/223718277-f7d6d1dc-5898-4bf1-bc27-390c7d4db7d9.png)
![Minecraft_ 1 19 2 - Multiplayer (3rd-party Server) 08_03_2023 09_52_50](https://user-images.githubusercontent.com/20447581/223718281-4516e1e9-475b-4305-9489-f0a487f52361.png)

**Comment by Shadows-of-Fire** [comment]
Is your original deep learner in a curios slot?  I think the grave pickup may attempt to place it there.
