### ISSUE TITLE
Energy Levels Critical 

### ISSUE THREAD

**Issue by th3c0ncept** [Shadows-of-Fire/Hostile-Neural-Networks#33]
Ender Dragon Model always puts the error "System Energy levels critical" whilst beeing on a reactor cable.
Please Help 

Modpack Greed The Recourse 4 (1.16.5)

**Comment by Shadows-of-Fire** [comment]
If the energy buffer is full and you are still receiving this error, it means the max buffer size needs to be increased.  The buffer size needs to be at least 200x the simulation cost of the highest simulation cost amongst all models.

You should report this to the developer of the modpack.
