### ISSUE TITLE
Change existing Data Model

### ISSUE THREAD

**Issue by Draxial** [Shadows-of-Fire/Hostile-Neural-Networks#34]
Is it possible to change the existing Data Models? I'm helping with the development of ATMVB and one of our issues is that the resourceful chickens mod we added. replace the vanilla chicken with their own chicken, thus not being accepted. https://github.com/AllTheMods/VolcanoBlock/issues/72

**Comment by Shadows-of-Fire** [comment]
Data models can be overridden via datapack like any datapackable object.
