### ISSUE TITLE
[1.20.1] Crash with Rubidium while scrolling JEI pages.

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Hostile-Neural-Networks#35]
`("GhostVertexBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter")`

### Versions:
MC: 1.20.1
Forge(not Neo): 47.1.3
Hostile Neural Networks: 5.1.3 | https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks/files/4711380
Placebo: 8.3.5
Rubidium: 0.6.5
JEI: 15.2.0.25
EMI: 1.0.19 (happens without too, just JEI.)

### Crash Reports
**Link with EMI:** https://gist.githubusercontent.com/Gbergz/b74cbe71a550ee87d9971a2db281dfa6/raw/c365dcc299b373197222bf974ac2d5709a3ed3f9/gistfile1.txt
**With just JEI:** https://gist.githubusercontent.com/Gbergz/41dafd9bdd1b28f49c943e8938059e3e/raw/a435640e185ce449eccd0c189b163f0aa0a1c8e0/gistfile1.txt

**Crash Report when right clicking an entity to build a data model:**
https://gist.githubusercontent.com/Gbergz/91d4a26cc9df89753aa53955d89b9ec9/raw/dd0de620d8a3781baf935535fd0aebe70f6ce6b4/gistfile1.txt

### Other info:
Seems to be ticking some datamodel from Twilight Forest, specifically an entity with ID: `twilightforest:stable_ice_core`.

EDIT:
Seems to be any datamodel.

**Comment by MatheusAmelco** [comment]
Exactly the same here.

MC: 1.20.1
Forge(not Neo): 47.1.3
Hostile Neural Networks: 5.1.3
Placebo: 8.3.5
Rubidium: 0.6.5
Rubidium Extra: 0.4.20-build.91
JEI: 15.2.0.26

Crash Report: https://gist.githubusercontent.com/MatheusAmelco/70807f51e623231cb73a2e3c2a9a27b3/raw/69e11c6f0cfe9b4a69c4b34bf888dee38304a73b/crash-2023-08-19_17.26.05-client.txt

**Comment by Shadows-of-Fire** [comment]
That's a rubidium bug, I cannot fix it.
