### ISSUE TITLE
Make HUD Element movable

### ISSUE THREAD

**Issue by Stray216** [Shadows-of-Fire/Hostile-Neural-Networks#36]
https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/blob/8c200dc9586663ecb5198a6ac6e4ef3fef580173/src/main/java/dev/shadowsoffire/hostilenetworks/client/DeepLearnerHudRenderer.java#L55C1-L57C19

I haven't spent a long time studying the code so I could be wrong. It seems like the HUD element is being rendered at those hardcoded values. Making the HUD movable could be as easy as making a separate client-config and putting those hardcoded values in it. Or you could implement a new command, maybe something like "/hostilenetworks hud_position [x] [y] [spacing]". Another idea would be a new button that launches a nice repositioning-menu inside the Deep Learner GUI, however just a config and a command would be sufficient for my case.

I would be happy with whatever as long as the HUD is movable.

**Comment by nailfor** [comment]
I play ATM8, the HUD hides important information, it would be cool to be able to move the window

**Comment by devout38** [comment]
> I play ATM8, the HUD hides important information, it would be cool to be able to move the window

This is an issue, agreed.  A keybind to toggle HUD on/off while in curio slot would solve this as well.

Edit: I say "solve" but it would still cover important info. It would be less painful if I could toggle it. I would prefer it not cover the main HUD at all.

**Comment by BigFatWizard** [comment]
Second that. Especially with the way the UI is designed, it's almost impossible to really see anything under it.
