### ISSUE TITLE
[1.19.2] Tooltip bug with the Enhanced Boss Bars resource pack

### ISSUE THREAD

**Issue by vizthex123** [Shadows-of-Fire/Hostile-Neural-Networks#37]
When using [said resource pack](https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars), the tooltips for the Wither and Ender Dragon prediction item render incorrectly.

![image](https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/assets/31721920/81ca223b-faf4-45bf-813a-09b7c4454444)

![image](https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/assets/31721920/552e17ea-322d-4e16-ba34-c7f8c1fbded8)

**Comment by Shadows-of-Fire** [comment]
Uh, think this might be outside of my control.  The tooltips aren't special on a per-model basis.

**Comment by vizthex123** [comment]
> Uh, think this might be outside of my control. The tooltips aren't special on a per-model basis.

hm, alright then. Guess I'll tell the resource pack's dev.
