### ISSUE TITLE
[1.19.2] This could use Deep Mob Learning's comprehensive config

### ISSUE THREAD

**Issue by vizthex123** [Shadows-of-Fire/Hostile-Neural-Networks#38]
I personally loved the config DML had, and it's one reason I always used it - however, this has basically no options you can change, which is a shame.

It'd be great if we got a config akin to DML's - setting custom variants of mobs, adding/removing loot from the Fabricator, changing the TF usage per-tier of each model, etc.

**Comment by Shadows-of-Fire** [comment]
All of these can be accomplished by using a datapack to change the data models https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/tree/1.19/src/main/resources/data/hostilenetworks/data_models

**Comment by vizthex123** [comment]
god, why it always a datapack :'c

**Comment by Shadows-of-Fire** [comment]
Because that is the direction Mojang has opted for Minecraft to take.
