### ISSUE TITLE
[Enhancement] Add Tag support on loot fabrication of predictions

### ISSUE THREAD

**Issue by DevDyna** [Shadows-of-Fire/Hostile-Neural-Networks#40]
I have a list of many items that i have decided to add on a single prediction 
So i have decided to tag all items and looping to extract all of them (because i need to use them on other things using kubejs) but i have founded that predictions don't support `"tag" : "#modname:itemstack"` 
(i have already check any other problems before send this issue like item limit on gui but didn't cause any issue)

[version : 1.19.2 , latest]

**Comment by vizthex123** [comment]
That could be neat (alongside NBT support if it's not already a feature).

**Comment by Shadows-of-Fire** [comment]
Recipe outputs, in general, do not support tags as an output concept since they need to produce an explicit item stack. I don't think I'll be changing that paradigm here.
