### ISSUE TITLE
Failed parsing data_models file hostilenetworks

### ISSUE THREAD

**Issue by Crayonan** [Shadows-of-Fire/Hostile-Neural-Networks#43]
A part of the data models are missing in my single player world, when right clicking a mob (which is already not  showing in JEI/REI, it says: _**no known models exist for this specimen**_

![image](https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/assets/78920025/3184bb84-1149-4adf-984d-958992adf6f5)

When looking at the log it also says: **Failed parsing data models file hostile networks:phantom** (and for all the other mobs not present)

Here are the data models that do get loaded:

![image](https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/assets/78920025/03544ed1-6f84-4334-a93a-52b14ca0b1b3)

Here is the log from starting my modpack, loading the sp world and right clicking a data model on the mob. 

[Log on mclo.gs](https://mclo.gs/f7uQzIa)

**Comment by Shadows-of-Fire** [comment]
You are missing the `entity` key on your data model json file.  Unfortunately the error is useless since it doesn't name the problem, so I can go update that.
