### ISSUE TITLE
More customisable tiers

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [Shadows-of-Fire/Hostile-Neural-Networks#47]
For a modpack I am working on, I would like to use HNN to allow for passive resource generation, but the current cap values for prediction chances are a bit too high for my liking. Additionally, I think it would be great as well to be able to change the "defaults" for the required data per tier and data given per-kill using maybe a config option. Could that be something that's possible without a larger refactor?

**Comment by RoyalReject** [comment]
I believe what you are asking for is already available through datapacks, unless I am misunderstanding https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/blob/1.19/src/main/resources/data/hostilenetworks/data_models/bat.json#L30-L41

**Comment by MaxNeedsSnacks** [comment]
Not really, since models without these values defined will pull from the tier defaults. Also, the predication chance caps definitely aren't a thing yet
