### ISSUE TITLE
Add Keybind to Open Deep Learner While in Baubles

### ISSUE THREAD

**Issue by RacerDelux** [Shadows-of-Fire/Hostile-Neural-Networks#49]
Currently there is a baubles slot for the deep learner, but there is no key binding to open it.

It would be nice if we had such a key bind.

**Comment by vizthex123** [comment]
I was really disappointed to find that there wasn't one, so I'd love to have this.

**Comment by RacerDelux** [comment]
> I was really disappointed to find that there wasn't one, so I'd love to have this.

It looks like this is now a feature, rejoice!

Thanks @Shadows-of-Fire !!!!
