### ISSUE TITLE
Items inside the simulation chamber disappear after unloading the block

### ISSUE THREAD

**Issue by TheDyreBanana** [Shadows-of-Fire/Hostile-Neural-Networks#5]
Unloading the chunk the block is placed in will reset its inventory. I haven't tested this with the loot chamber but I imagine it happens with it too.

**Comment by Shadows-of-Fire** [comment]
what version?

**Comment by TheDyreBanana** [comment]
1.18.1

**Comment by Shadows-of-Fire** [comment]
mod version

**Comment by TheDyreBanana** [comment]
3.03
