### ISSUE TITLE
[Suggestion] Please add a config option to disable colors of mob names in texts

### ISSUE THREAD

**Issue by YocyCraft** [Shadows-of-Fire/Hostile-Neural-Networks#58]
In some situation, some texts of mob names are too black to be readable, for example in ATM10 modpack:

![2024-09-05_01 26 10](https://github.com/user-attachments/assets/a7659903-d1e3-4f6c-bd07-9b8d946c1465)

For a mod released for 3 years with 16.9M downloads, it's incredible that nobody has mentioned this issue before. However, please add a config option for readability, it's very crucial for accessibility of players.

**Comment by MatthiasMann** [comment]
Can this be back ported to 1.20.1 please?
