### ISSUE TITLE
deep learner not accepting curio anymore

### ISSUE THREAD

**Issue by Darwin-Gabriel** [Shadows-of-Fire/Hostile-Neural-Networks#61]
i can't put deep learner on the deep lerner curio slot
Neoforge: 21.1.54
hostile neural networks: 6.0.1
placebo 9.5.2

**Comment by Shadows-of-Fire** [comment]
Curios are not currently supported due to the abandonment of the official Curios project.  I've elected not to make a change towards either of the forks for the time being.
