### ISSUE TITLE
[1.20.1] Simulation Chamber breaks NBT tags in other inventories

### ISSUE THREAD

**Issue by RingOfSouls** [Shadows-of-Fire/Hostile-Neural-Networks#63]
I played for a while on the Forge 1.20.1 modpack with HNN, already set up automation, and started noticing that some resources stopped stacking and being recognized for autocrafting in the AE2 system.

After investigating, I figured out that the Simulation Chamber, upon placement and subsequent ticks, inserts the NBT tag 'data_model' into all ItemStack.EMPTY items in nearby inventories, including the player’s inventory. However, I was unable to figure out how this tag is being added to the items.

How to reproduce the bug:
- Install Forge 1.20.1 client
- Install mods HNN-5.3.1, Placebo-8.6.2, CraftTweaker-14.0.43 (the last one to check NBT tags of slots)
- Run the /ct hand command and ensure there’s no additional NBT tag
- Place the Simulation Chamber block and go through the slots using the /ct hand command

![2024-09-24_10 59 18](https://github.com/user-attachments/assets/d3c9f2a8-6984-492e-81d7-fd67ffdf0835)
![2024-09-24_10 59 25](https://github.com/user-attachments/assets/31953a18-74e3-4065-af45-1c4dc5c4f9ba)

**Comment by Shadows-of-Fire** [comment]
It's probably just mutating the global ItemStack.EMPTY field.  What side effects is this causing?  The empty stack is always empty regardless of any junk nbt that might be attatched to it

**Comment by RingOfSouls** [comment]
![image](https://github.com/user-attachments/assets/783a8ce1-c086-4f4a-b797-5abc84f29b5e)
In some cases, this happens. Somehow, this NBT tag gets added to existing items. I don’t know how it happens, but they stop stacking, and the ME system stops recognizing them if they are used for crafting items or set in bus filters.
