### ISSUE TITLE
[BUG] v5.3.2 - Loot Fabricator makes loot infinitely without requiring predictions

### ISSUE THREAD

**Issue by Nivid-IT** [Shadows-of-Fire/Hostile-Neural-Networks#71]
After setting the desired output by inserting one prediction into a loot fabricator, it then proceeds to create more loot out of thin air while supplied with energy, without requiring any predictions. Likely a logic issue introduced in https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/commit/37aff6828c72b837940ff274792556b1dc46cd53.

**Comment by Shadows-of-Fire** [comment]
db5add57d3a9d085579f19bdab2598b77aa4d769
