### ISSUE TITLE
Freezes with equipped Deep Learner in ATM6 (Minecraft 1.16.5)

### ISSUE THREAD

**Issue by ghostbear77** [Shadows-of-Fire/Hostile-Neural-Networks#9]
I am playing the ATM6 Modpack with HNN 1.06 installed.

Every time I put the Deep Learner into my inventory the game starts to eat up a lot more memory (I have 8G assigned to the pack). After a while the memory fills up completely and I recieve a 5-10 sec freeze (not just fream drops, but the whole game stops) until the garbage collector frees enough to go on. This repeats in slightly irregularly but with increased frequency when i continue to collect kills with the Item equipped. After just one ingame night i can only walk 10 blocks before the next freeze happens.

Even after unequipping the Deep Learner and storing it in a chest (or Backpack) the freezes do not completely stop until a game restart, That is why i am not sure if it is an actual proplem with Hostile-Neural-Networks or something the pack added in configuration.

**Comment by Shadows-of-Fire** [comment]
Thanks for reporting this - you're actually right, there appear to be an issue with some caching I'm doing for rendering.  I have the fix ready, I just need to push it to both 1.18 and 1.16
